services:
  daylightsticot:
    build: .
    ports:
      - "127.0.0.1:8701:8000"
    develop:
      watch:
        - action: sync
          path: ./daylightsticot/templates/
          target: /daylight/daylightsticot/templates/
  valkey:
    image: valkey/valkey:8.0.1
    command: valkey-server /usr/local/etc/valkey/valkey.conf
    expose: 
      - "6379"
    volumes:
      - ./valkeyconf/valkey.conf:/usr/local/etc/valkey/valkey.conf

