services:
  daylightsticot:
    build: .
    ports:
      - "8701:8000"
  valkey:
    image: valkey/valkey:8.0.1
    command: valkey-server /usr/local/etc/valkey/valkey.conf
    expose: 
      - "6379"
    volumes:
      - ./valkeyconf/valkey.conf:/usr/local/etc/valkey/valkey.conf

